version: "3.7"
services:
    mysql:
        image: mysql:8.0
        container_name: nik.mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - mysqldata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        networks:
            - nik_net
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: nik.phpmyadmin
        environment:
            PMA_HOST: db
            MYSQL_USER: "xchengine"
            MYSQL_PASSWORD: "123123"
        ports:
            - "8191:80"
    redis:
        image: redis:6-alpine
        container_name: nik.redis
        ports:
            - 6378:6379
        networks:
            - nik_net
    php:
        build:
            context: .
            target: php
        container_name: nik.php
        links:
            - redis
            - mysql
        volumes:
            - ./:/var/www/html/
        networks:
            - nik_net
    php_worker:
        build:
            context: .
            target: php_worker
        container_name: nik.php_worker
        links:
            - redis
            - mysql
        restart: always
        volumes:
            - ./docker/supervisor/queue.conf:/etc/supervisor/queue.conf
            - ./:/var/www/html/
        networks:
            - nik_net
    nginx:
        build:
            context: .
            target: nginx
        container_name: nik.nginx
        links:
            - php
        ports:
            - 8010:80
        networks:
            - nik_net
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public

networks:
    nik_net:
        driver: bridge
volumes:
    mysqldata:
        driver: local
